# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 73c745bb5066eb6bd00c0a372a7c49840dd4d27c663c9a28ea0e0fca007e722c4eb2cea9a3e8b10cdd1fe1b7142dd0b351e9375d48ff5d65328bd17a9a7961f8

test:
  secret_key_base: 3e479a5d9365c0d2c98adbf815c9b96592d2db2f1e25f894c468b1fb14815d3a7811ab00dd1266657ae4a6288425462b4f927f0bde133d8d1529f7ba8b8e0768

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
